[tool.ruff]
line-length = 100

[tool.ruff.lint] #https://docs.astral.sh/ruff/rules
extend-select = ["E501"]

[tool.mypy]
exclude = [
  'src/.*_excluded.py$'
]

[tool.bandit]
exclude_dirs = [
  "src/bandit_excluded.py",
  "test"
]

[tool.pytest.ini_options]
addopts = """
          --cov-fail-under=100 \
          --cov-report=xml \
          --cov-report=term-missing \
          --cov-config=.coveragerc
          """
