name: CI/CD python-linting 

on:
  push: 
    branches: [ "**" ]
    paths: 
      - 'python-linting/**'
  pull_request: 
    branches: [ main ] 
    paths: 
      - 'python-linting/**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    defaults:
      run:
        working-directory: ./python-linting

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: 'python-linting/requirements.txt'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with Ruff
      run: |
        ruff check . --output-format=github

    - name: Static type checking with mypy 
      run: |
        mypy src 

    - name: Static code analysis (security) with bandit
      run: |
        bandit -r src -c pyproject.toml

    - name: Test with pytest and generate coverage report
      run: |
        pytest --cov=.
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-${{ matrix.python-version }} # Unique name per Python version
        path: python-linting/coverage.xml
        if-no-files-found: error
